version: '3.8'

services:
  postgres:
    image: postgres
    container_name: api-framework
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - api-framework-network

networks:
  api-framework-network:

volumes:
  api-framework-volume:
